FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache python3 make g++ git sqlite-dev
COPY package*.json ./
RUN npm install --build-from-source sqlite3
RUN npm install
COPY . .
EXPOSE 8080
CMD ["npm", "start"]
